CREATE SEQUENCE IF NOT EXISTS chat_message_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS review_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE advertisement
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    advertisement_id UUID,
    title            VARCHAR(255),
    description      VARCHAR(2000),
    image            VARCHAR(500),
    price            DECIMAL,
    category_id      INTEGER                                  NOT NULL,
    location         VARCHAR(255),
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    active           BOOLEAN                                  NOT NULL,
    user_id          INTEGER                                  NOT NULL,
    CONSTRAINT pk_advertisement PRIMARY KEY (id)
);

CREATE TABLE advertisement_favorites
(
    advertisement_id INTEGER NOT NULL,
    user_id          INTEGER NOT NULL,
    CONSTRAINT pk_advertisement_favorites PRIMARY KEY (advertisement_id, user_id)
);

CREATE TABLE category
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(255),
    description     VARCHAR(255),
    parent_category VARCHAR(255),
    category_id     UUID,
    CONSTRAINT pk_category PRIMARY KEY (id)
);

CREATE TABLE chat_message
(
    id           BIGINT  NOT NULL,
    sender_id    INTEGER NOT NULL,
    recipient_id INTEGER NOT NULL,
    content      VARCHAR(255),
    timestamp    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_chatmessage PRIMARY KEY (id)
);

CREATE TABLE images
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    advertisement_id INTEGER                                  NOT NULL,
    key              VARCHAR(1024),
    url              VARCHAR(1024),
    thumbnail_key    VARCHAR(1024),
    thumbnail_url    VARCHAR(1024),
    sort_order       INTEGER,
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    content_type     VARCHAR(255),
    size             BIGINT,
    image_id         UUID,
    CONSTRAINT pk_images PRIMARY KEY (id)
);

CREATE TABLE refresh_token
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token    VARCHAR(255),
    expires  TIMESTAMP WITHOUT TIME ZONE,
    users_id INTEGER                                  NOT NULL,
    CONSTRAINT pk_refreshtoken PRIMARY KEY (id)
);

CREATE TABLE review
(
    id               BIGINT  NOT NULL,
    trade_id         BIGINT  NOT NULL,
    reviewer_id      INTEGER NOT NULL,
    reviewed_user_id INTEGER NOT NULL,
    review_id        UUID,
    rating           INTEGER,
    comment          VARCHAR(500),
    CONSTRAINT pk_review PRIMARY KEY (id)
);

CREATE TABLE trade
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    trade_id                UUID,
    advertisement_id        INTEGER,
    seller_id               INTEGER,
    buyer_id                INTEGER,
    status                  VARCHAR(255),
    created_at              TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at              TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    proposed_price          DECIMAL,
    seller_left_review      BOOLEAN                                 NOT NULL,
    buyer_left_review       BOOLEAN                                 NOT NULL,
    buyer_marked_completed  BOOLEAN                                 NOT NULL,
    seller_marked_completed BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_trade PRIMARY KEY (id)
);

CREATE TABLE users
(
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255),
    email          VARCHAR(255),
    password       VARCHAR(255),
    role           VARCHAR(255),
    user_id        UUID,
    rating_count   INTEGER                                  NOT NULL,
    average_rating DOUBLE PRECISION                         NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE advertisement
    ADD CONSTRAINT FK_ADVERTISEMENT_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES category (id);

ALTER TABLE advertisement
    ADD CONSTRAINT FK_ADVERTISEMENT_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE chat_message
    ADD CONSTRAINT FK_CHATMESSAGE_ON_RECIPIENT FOREIGN KEY (recipient_id) REFERENCES users (id);

ALTER TABLE chat_message
    ADD CONSTRAINT FK_CHATMESSAGE_ON_SENDER FOREIGN KEY (sender_id) REFERENCES users (id);

ALTER TABLE images
    ADD CONSTRAINT FK_IMAGES_ON_ADVERTISEMENT FOREIGN KEY (advertisement_id) REFERENCES advertisement (id);

ALTER TABLE refresh_token
    ADD CONSTRAINT FK_REFRESHTOKEN_ON_USERS FOREIGN KEY (users_id) REFERENCES users (id);

ALTER TABLE review
    ADD CONSTRAINT FK_REVIEW_ON_REVIEWED_USER FOREIGN KEY (reviewed_user_id) REFERENCES users (id);

ALTER TABLE review
    ADD CONSTRAINT FK_REVIEW_ON_REVIEWER FOREIGN KEY (reviewer_id) REFERENCES users (id);

ALTER TABLE review
    ADD CONSTRAINT FK_REVIEW_ON_TRADE FOREIGN KEY (trade_id) REFERENCES trade (id);

ALTER TABLE trade
    ADD CONSTRAINT FK_TRADE_ON_ADVERTISEMENT FOREIGN KEY (advertisement_id) REFERENCES advertisement (id);

ALTER TABLE trade
    ADD CONSTRAINT FK_TRADE_ON_BUYER FOREIGN KEY (buyer_id) REFERENCES users (id);

ALTER TABLE trade
    ADD CONSTRAINT FK_TRADE_ON_SELLER FOREIGN KEY (seller_id) REFERENCES users (id);

ALTER TABLE advertisement_favorites
    ADD CONSTRAINT fk_advfav_on_advertisement FOREIGN KEY (advertisement_id) REFERENCES advertisement (id);

ALTER TABLE advertisement_favorites
    ADD CONSTRAINT fk_advfav_on_users FOREIGN KEY (user_id) REFERENCES users (id);